### ISSUE TITLE
React Support?

### ISSUE THREAD

**Issue by thelinuxlich** [hannoeru/vite-plugin-pages#11]
I wrote a poor man autorouting for my react starter https://github.com/thelinuxlich/react-modern-starter/blob/main/src/AutoRouting.jsx but could leverage this one maybe!

**Comment by hannoeru** [comment]
Sorry, I am not familiar with React.
But looks like you can write a React version of vite-plugin-pages,
then using `react-router-config` to add generated routes.

**Comment by frandiox** [comment]
@hannoeru It might not be very hard to support React if you are interested.  I'm using `react-router-config` in Vite SSR library and looks like the only difference with Vue routes is that nested routes are called `route.routes` instead of `route.children`.

And of course, instead of parsing Vue SFC looking for a route block, it could just import a named const from a JSX file.

**Comment by hannoeru** [comment]
Ok, I will check it when I have time.
