### ISSUE TITLE
Update to v0.21.0 breaks the build because of route lang="json" blocks

### ISSUE THREAD

**Issue by kouts** [hannoeru/vite-plugin-pages#178]
Hello, thanks for your great work in this vite plugin.
In version 0.20.2 `<route lang="json">` blocks work ok and is an easy way to get syntax highlighting.
In version 0.21.0 using `<route lang="json">`  produces an error `SyntaxError: import not found: default`

Here's a reproduction
https://stackblitz.com/edit/github-ijnjm5-3ce2um?file=src/pages/index.vue

**Comment by hannoeru** [comment]
This is related to [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components),
looks like they added this comment to route block, which shouldn't be happening.
<img width="651" alt="スクリーンショット 2022-03-02 2 36 47" src="https://user-images.githubusercontent.com/16288797/156220394-e97db528-639c-4a39-bd2a-ef3af7a7e5df.png">

**Comment by kouts** [comment]
In my local project where this is happening I don't have `unplugin-vue-components` installed so it must be something else. I'll try to reproduce it in another Stackblitz.
Thanks @hannoeru

**Comment by kouts** [comment]
That fixed it @hannoeru, thanks

**Comment by LukasKnuth** [comment]
Reopening because I have the same error (also using `unplugin-vue-components` in my project) but I'm using `lang="yaml"` which still fails with `"vite-plugin-pages": "^0.21.2"`.

Since you fixed this specifically for the JSON plugin, is it possible that a specific fix for YAML is required as well?

---

I have observed a lot of weird behaviour with this.

1. It only fails for Markdown components transformed with https://github.com/antfu/vite-plugin-md
2. It fails for the Markdown block if I don't put text with spaces into `"` quotes.
3. If I quote all text, I get the above mentioned `no default export` error.

**Comment by hannoeru** [comment]
@LukasKnuth cab you provide a reproduction?

**Comment by LukasKnuth** [comment]
@hannoeru I have made https://github.com/LukasKnuth/codeislandorg_vue public. If you update `"vite-plugin-pages": "^0.21.2"` and run `npm run build`, you'll get the error. The markdown pages are under `src/pages/blog`.

Let me know if you need more info

**Comment by hannoeru** [comment]
@LukasKnuth fixed, try v0.21.3.

**Comment by LukasKnuth** [comment]
@hannoeru It works. Crazy how fast you are on these changes, much appreciated!
