### ISSUE TITLE
vite load chunk error after new build (Failed to fetch dynamic imported modules)

### ISSUE THREAD

**Issue by liho00** [hannoeru/vite-plugin-pages#247]
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/77238199/176231413-36991792-9433-4e6a-a057-fa9237fbeb70.png">

Step to reproduce:
1. Build and serve the app on localhost
2. Change content of a selected file route
3. Build again
4. Click the link to the selected route that had been changed content.
5. Blank screen shown

**Comment by hannoeru** [comment]
Can you provide a repo with the code required to reproduce this issue?

**Comment by zhuhaobam** [comment]
```
X
[id].vue  Failed to fetch dynamic imported modules
```

```

-------[id]
----------index.vue
```
@liho00 I've been working on it for a long time. It's the only thing I can do

**Comment by zhuhaobam** [comment]
The possible cause is the bug caused by the underlined beginning
[id].vue  The JS accessed after Vue compilation is   _ id*********.js ,start with _

**Comment by hannoeru** [comment]
Can anyone provide a [minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example) for me to debug?

**Comment by zhuhaobam** [comment]
The GitHub page may be accessed normally
my page    https://zhuhaobam.github.io

![image](https://user-images.githubusercontent.com/15319171/187026363-19f79fcc-52ec-427a-b7a9-2f1c1da04693.png)

**Comment by zhuhaobam** [comment]
my project https://github.com/zhuhaobam/vtdd

**Comment by aizigao** [comment]
I resolve it, i use vue3 with vite, this is my config 


```ts
 
import Pages, { vueResolver } from 'vite-plugin-pages'


export default defineConfig(() => {
  return {
    plugins: [
      Pages({
        extensions: ['vue', 'md'],
        exclude: ['**/components/*.vue'],
        importMode(filepath, options) {
          for (const page of options.dirs) {
            if (page.baseRoute === '') {
              if (filepath.match(new RegExp(`/${page.dir}/([\\w-]+/)?index`))) {
                return 'sync'
              }
              // ========================= look this ====================
              // set load-fail.vue to sync
              if (filepath.match(new RegExp(`/${page.dir}/load-fail`))) {
                return 'sync'
              }
            }
          }
          return 'async'
        },
        resolver: {
          ...vueResolver(),
          stringify: {
            // -------------------- edit this------------------
            dynamicImport: (importPath: string) => {
              return `() => import("${importPath}")
              .then((m) => m.default)
              .catch((e)=>
                import('/src/pages/load-fail.vue')
              )`
            }
          }
        }
      })
    ]
  }
})
```

**Comment by andrioid** [comment]
This also happens for React projects. We first noticed it after adding Sentry to the project, but it can be easily reproduced by.

1. npm run build
2. npm run preview
3. Visit the site
4. Change the asset file names from the default values. You could also change the contents for each file, but is a more reliable way of changing the hashes.
    ```
    build: {
        rollupOptions: {
            // You need to change this between build runs to reproduce
            chunkFileNames: `assets/[name]-[hash].js`
            entryFileNames: `assets/[name]-[hash].js`
        }
    }
    ```
5. Then navigate to a page that is dynamically, but hasn't been loaded yet. You should see a "Failed to fetch dynamically imported module" in the console.

My current work-around is to catch the error in an error-boundary and reload the window. It works, but I'm not happy about it.

Another option is to disable the hashing, by repeating step 4 and remove the `[hash]` from the filenames. That can however result in weird cases where parts of your application have different versions (due to caching).

This is a weird situation, that probably won't occur if you're using a CDN (previous hashes will still be loadable). But, if you're deploying into containers where the previous container is wiped after deployment. This will happen every time you deploy.

**Comment by silverwind** [comment]
For reference, https://github.com/vitejs/vite/pull/12084 is the actual fix for this.
