### ISSUE TITLE
Reduce the large bundle size

### ISSUE THREAD

**Issue by Plumbiu** [hannoeru/vite-plugin-pages#479]
### Description

I use react and it doesn't use yaml or else, the original bundle size is over 1mb

<img width="608" alt="image" src="https://github.com/hannoeru/vite-plugin-pages/assets/99574369/48784ab1-7909-41ac-ba5d-de88a2195189">

### Suggested solution

Export react, vue, sollid ... plugins, like:

```ts
import { reactPages, vuePages } from 'vite-plugin-pages'
```

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hannoeru** [comment]
That is frontend bundle size, not plugin it self.
Because we are import pages in to one file that generate routes, you can use importMode async to reduce bundle size.
Will close this as this is not a issue to this plugin. If you want some help you can open a [Discussions](https://github.com/hannoeru/vite-plugin-pages/discussions) to ask for help.
